[debug]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log_level = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log_level = "critical"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
